# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52172935a6c9aa9eb5bb210c01a18ba5a6c14514a284bf154ec60c2e79c690a6f49d6a76fca0512436ebad58ef0e634f7abbc539da88aa83b95b133f1ee6e1c7

test:
  secret_key_base: 7e57df5c25fe9c458e4f980727a595a8825cf364494bc34d6f41e6a82891b1b9c0501e7a36c1ad6db34750ba47719e7eac1df4e6415768c6be11f59ab43b9c51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
